### ISSUE TITLE
exciting but how about docs? :)

### ISSUE THREAD

**Issue by innerop** [juliantrue/radius#1]
Hi there,

I'd love to try this on my TX2 and on top of the Redtail setup. Just really not sure where to start.

**Comment by juliantrue** [comment]
Hey there,

happy to hear about your interest in our project, this repo is currently a work in progress and is not quite ready to be run in its entirety. Once we have sufficient progress, we will be posting full usage documentation. Current timeline is putting that around late April! My apologies about not making the above explicit, I shall update the README with this information to prevent future confusions
